[package]
name = "example_prebuild"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
thiserror = { workspace = true }
copager = { path = "../..", features = ["derive", "regexlex", "lr1", "sexp"] }

[build-dependencies]
serde = { workspace = true }
copager = { path = "../..", features = ["derive", "regexlex", "lr1"] }
