[package]
name = "copager"
version = "0.1.1"
edition = "2021"

[dependencies]
copager_core = { path = "./crates/core" }
copager_algorithm = { path = "./crates/algorithm" }
copager_algorithm_lr1 = { path = "./crates/algorithm_lr1" }
copager_cfg = { path = "./crates/cfg" }
copager_cfg_derive = { path = "./crates/cfg_derive" }
copager_lex = { path = "./crates/lex" }
copager_lex_regex = { path = "./crates/lex_regex" }
copager_ir = { path = "./crates/ir" }
copager_ir_sexp = { path = "./crates/ir_sexp" }

[dev-dependencies]
anyhow = { workspace = true }
serde = { workspace = true }
serde_json = "1.0.117"

[features]
default = []

[workspace]
resolver = "2"
members = [
    "./crates/core",
    "./crates/algorithm",
    "./crates/algorithm_lr1",
    "./crates/cfg",
    "./crates/cfg_derive",
    "./crates/lex",
    "./crates/lex_regex",
    "./crates/ir",
    "./crates/ir_sexp",
]
exclude = []

[workspace.dependencies]
anyhow = "1.0.82"
thiserror = "1.0.58"
serde = { version = "1.0.197", features = ["derive"] }
regex = "1.10.4"
regex-macro = "0.2.0"
