[package]
name = "copager"
version = "0.1.1"
edition = "2021"

[dependencies]
copager_core = { path = "./crates/core" }
copager_algorithm = { path = "./crates/algorithm" }

[dev-dependencies]
anyhow = { workspace = true }
serde = { workspace = true }
serde_json = "1.0.117"

[features]
default = []
derive = ["copager_core/derive"]

[workspace]
resolver = "2"
members = [
    "./crates/core",
    "./crates/algorithm",
]
exclude = []

[workspace.dependencies]
anyhow = "1.0.82"
thiserror = "1.0.58"
serde = { version = "1.0.197", features = ["derive"] }
regex = "1.10.4"
regex-macro = "0.2.0"
