[package]
name = "copager_parse_common"
edition = "2024"
version.workspace = true

[dependencies]
anyhow = { workspace = true }
thiserror = { workspace = true }
copager_lang = { path = "../lang" }

[dev-dependencies]
copager_lang = { path = "../lang", features = ["derive"] }
