[package]
name = "copager_parse_common"
edition = "2024"
version.workspace = true

[dependencies]
anyhow = { workspace = true }
thiserror = { workspace = true }
copager_cfl = { path = "../cfl" }

[dev-dependencies]
copager_cfl = { path = "../cfl", features = ["derive"] }
