[package]
name = "example_oneshot"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
thiserror = { workspace = true }
copager = { path = "../..", features = ["derive", "regexlex", "lr1", "sexp"] }
