[package]
name = "copager_ir_tree"
edition = "2021"
version.workspace = true

[dependencies]
serde = { workspace = true, features = ["derive"] }
copager_lang = { path = "../lang" }
copager_lex = { path = "../lex" }
copager_parse = { path = "../parse" }
copager_ir = { path = "../ir", features = ["derive"] }
copager_utils = { path = "../utils" }

[dev-dependencies]
anyhow = { workspace = true }
copager_core = { path = "../core" }
copager_lang = { path = "../lang", features = ["derive"] }
copager_lex_regex = { path = "../lex_regex" }
copager_parse_lr_lr1 = { path = "../parse_lr_lr1" }
copager_ir_tree = { path = "." }
