[package]
name = "example_prebuild_grammar"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
thiserror = { workspace = true }
serde = { workspace = true }
copager = { path = "../../..", features = ["derive", "regexlex", "lr1", "sexp"] }
