[package]
name = "copager_utils"
version = "0.3.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
thiserror = { workspace = true }
serde = { workspace = true }
copager_cfl = { path = "../cfl"}
