[package]
name = "copager_lex"
version = "0.3.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
thiserror = { workspace = true }
copager_cfl = { path = "../cfl" }
copager_utils = { path = "../utils" }
