[package]
name = "copager_core"
version = "0.1.1"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
thiserror = { workspace = true }
serde = { workspace = true, features = ["derive"]}
regex = { workspace = true }
copager_core_derive = { path = "../core_derive", optional = true }

[features]
default = []
derive = ["dep:copager_core_derive"]
