[package]
name = "copager_parse"
version = "0.1.1"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
thiserror = { workspace = true }
copager_cfg = { path = "../cfg" }
copager_lex = { path = "../lex" }
copager_utils = { path = "../utils" }
