FILEPATH =

# Publish (./docs/public)
publish:
	hugo

# Run (http://localhost:1313)
run:
	hugo server

# New Chapter
# - make chapter FILEPATH="chapter1/_index.md"
chapter:
	hugo new --kind chapter $(FILEPATH)

# New Article
# - make article FILEPATH="chapter1/article.md"
article:
	hugo new $(FILEPATH)
