[package]
name = "example_lang_json"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
thiserror = { workspace = true }
copager = { path = "../..", features = ["derive", "template", "lalr1", "sexp"] }
